#host: "rds-mysql-alloys.c2jdmok5sewf.us-east-2.rds.amazonaws.com"
#port: 3306
#dbname: "Oxygen_Evolution_Catalysts"
#user: "ase_aws"
#password: "soraya09"
#tablename: "metal_oxyde"
#id_colm : 'map_id' # name of the column with the structure id


host: '52.188.209.245'
password: '123456'
user: 'ctetsass'
port: 22