# host1:
    #   binaries:
    #       bin_name1: /path/to/bin1
    #       bin_name2: /path/to/bin2
    #   check_queue: /full/path/to/showq
    #   hostname: full.host.name
    #   ip_address: ###.###.##.###
    #   nodes: # of nodes on machine
    #   ppn: # of processors per node
    #   sub_script: /full/path/to/submission/command
    #   sub_text: filename for qfile to use a template.
    #            A file named "filename" must be in configuration/qfiles
    #   walltime: maximum walltime, in seconds
    # host2: ...

cedar:
  binaries:
    #vasp: /home/ctetsass/bin/vasp/vasp_std
    vasp_serial: /home/ctetsass/bin/vasp/vasp_std
  check_queue: qstat
  hostname: 'cedar.computecanada.ca'
  ip_address:
  nodes: 1
  ppn: 4
  sub_script: sbatch
  sub_text: /home/ctetsass/scratch/
  walltime:

graham:
  binaries:
    vasp_54:
    vasp_54_serial:
  check_queue: qstat
  hostname: 'graham.computecanada.ca'
  ip_address:
  nodes: 1
  ppn: 4
  sub_script: sbatch
  sub_text:
  walltime:

niagara:
  allocation:
    rrg-itamblyn-ab
  binaries:
    vasp_54:
    vasp_54_serial:
  check_queue: qstat
  hostname: 'niagara.computecanada.ca'
  ip_address:
  nodes: 1
  ppn: 4
  sub_script: sbatch
  sub_text:
  walltime: